sudo: required
language: csharp
solution: ExtjsWd/ExtjsWd.sln
install:
  - nuget restore ExtjsWd/ExtjsWd.sln
  - nuget install NUnit.Console -Version 3.5.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ExtjsWd/ExtjsWd.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./ExtjsWd.Test/bin/Release/ExtjsWd.Test.dll
